#!/bin/bash

case "$(uname -s)" in
Darwin)
  LOGFILE="${HOME}/Library/Application Support/Microsoft/Teams/logs.txt"
  ;;
Linux)
  LOGFILE="${HOME}/.config/Microsoft/Microsoft Teams/logs.txt"
  ;;
CYGWIN* | MINGW32* | MSYS* | MINGW*)
  echo "Windows OS not supported. Try https://github.com/EBOOZ/TeamsStatus."
  exit 1
  ;;
*)
  echo "OS not supported."
  exit 1
  ;;
esac

last_event=$(tac "${LOGFILE}" | grep -oh "eventData: s::;m::1;a::[0-9]" | head -n1)

if [[ "${last_event}" =~ 0$ ]] || [[ "${last_event}" =~ 1$ ]]; then
  #  echo "☎️ In a call"
  exit 0
else
  # echo "not in call"
  exit 1
fi
